### PR TITLE
Zgui primitive drawing

### PR DESCRIPTION
**Pull request by Bergasms**
I have mapped most of the primitive drawing functions. 

I Intend to add the primitive image functions at a later time as I expect I will need them.    
I did not add the path building drawing functions.     

The following can be used to test the primitive drawing.

        zgui.addLine([2]f32{ 0, 0 }, [2]f32{ 300, 300 }, 0xFFFF00FF, .{ .thickness = 2.0 });
        zgui.addRect([2]f32{ 10, 10 }, [2]f32{ 50, 20 }, 0xFFFF00FF, .{ .thickness = 2.0 });

        zgui.addRectFilled([2]f32{ 10, 40 }, [2]f32{ 50, 80 }, 0xFF00FFFF, .{});
        zgui.addRectFilledMultiColor([2]f32{ 10, 90 }, [2]f32{ 50, 120 }, .{
            .top_left = 0xFF00FFFF,
            .top_right = 0xFFFF0000,
            .bottom_right = 0xFF00FF00,
            .bottom_left = 0xFF0F0F0F,
        });

        zgui.addQuadFilled([2]f32{ 50, 10 }, [2]f32{ 100, 10 }, [2]f32{ 100, 50 }, [2]f32{ 50, 50 }, 0xFFF0F0FF, .{});
        zgui.addQuad([2]f32{ 50, 10 }, [2]f32{ 100, 10 }, [2]f32{ 100, 50 }, [2]f32{ 50, 50 }, 0xFF0000FF, .{});

        zgui.addTriangleFilled([2]f32{ 250, 10 }, [2]f32{ 300, 50 }, [2]f32{ 200, 50 }, 0xFFF0F0FF, .{});
        zgui.addTriangle([2]f32{ 250, 10 }, [2]f32{ 300, 50 }, [2]f32{ 200, 50 }, 0xFF0000FF, .{});

        zgui.addCircleFilled([2]f32{ 400, 300 }, 20, 0xFFFFFF00, .{});
        zgui.addCircle([2]f32{ 400, 300 }, 20, 0xFF000F00, .{});

        zgui.addText([2]f32{ 200, 300 }, 0xFFFF0000, "This is some text", .{});

        zgui.addBezierCubic([2]f32{ 150, 150 }, [2]f32{ 150, 250 }, [2]f32{ 100, 150 }, [2]f32{ 100, 250 }, 0xFF0000FF, 2.0, .{ .num_segments = 10 });
        zgui.addBezierQuadratic([2]f32{ 150, 150 }, [2]f32{ 150, 250 }, [2]f32{ 100, 150 }, 0xFF0000FF, 2.0, .{ .num_segments = 10 });

        const points = [3][2]f32{ [2]f32{ 100, 100 }, [2]f32{ 300, 100 }, [2]f32{ 300, 300 } };
        var ptr: [*]const [2]f32 = &points;

        zgui.addPolyline(ptr, 3, 0xFFFFFFFF, .Closed, 5.0, .{});
        zgui.addConvexPolyFilled(ptr, 3, 0xFF00FF00, 2.0, .{});
        
Please let me know your opinion on how I have handled accessing the intended drawing list. The function is as follows in zgui.cpp

        ImDrawList* drawList(char whichList) {

I wonder if it would be better to pass multiple location information (eg the points in a quad) as a struct with named parameters instead of just dumping the values directly into the function.

### CODE REVIEW

**Comment by ArtemisX64** [comment]
Looks fine to me

**Comment by ArtemisX64** [comment]
But I think the name of parameters could be more explicit. ie, for example, instead of p1, p2, p3 and p4, it is better if you use left, right, top, bottom. (Like other UI libs)

**Comment by ArtemisX64** [comment]
||I wonder if it would be better to pass multiple location information (eg the points in a quad) as a struct with named parameters instead of just dumping the values directly into the function.
I like this idea. (For making things explicit)

**Comment by Bergasms** [comment]
OK! I updated the functions to accept a struct with named parameters for the geometric inputs where sensible. This is a massive help for complicated things like the bezier drawing functions.

        zgui.addBezierCubic(.{
            .start = .{ 150, 150 },
            .control_start = .{ 150, 250 },
            .control_finish = .{ 100, 150 },
            .finish = .{ 100, 250 },
        }, 0xFF0000FF, 2.0, .{ .num_segments = 10 });
        zgui.addBezierQuadratic(.{
            .start = .{ 150, 150 },
            .control = .{ 150, 250 },
            .finish = .{ 100, 150 },
        }, 0xFF0000FF, 2.0, .{ .num_segments = 10 });

**Review by ArtemisX64 — APPROVED** [review]

**Pull request merged**
