### PR TITLE
Table support

### PR DESCRIPTION
**Pull request by Bergasms**
Hi, I'm using your library to build a GBA Sprite editor using zig (As a way to learn zig, mostly) and I needed basic support for the Table so I emulated your work to add it in.    

I'm unsure if this is useful to you (You are probably working on Tables yourself) but if it is that's great.   

Note the branch name reflects that I had added in support for Image as well but removed that as it conflicts with your implementation.

Thanks for the work so far.

### CODE REVIEW

**Comment by ArtemisX64** [comment]
Thanks for adding Table support. But I found some small issues with the implementation. Can you resolve it?

**Comment by Bergasms** [comment]
Yes let me know what I can change.   

If you like I can implement the whole Table section, I omitted some functions/params because I wasn't using them

**Comment by ArtemisX64** [comment]
> Yes let me know what I can change.
> 
> If you like I can implement the whole Table section, I omitted some functions/params because I wasn't using them

Can you add other paramteres too? You can refer my Image function which uses ImVec4 and ImVec2 as parameters. If you are confident that those values can be used as default values, I recommend creating a struct which holds those default parameters.
eg:
```zig
const myCustomTable = struct {
    rows: u32 = 0,
   columns: u32 ,
};

fn createTable(table: myCustomTable) void{
   zguiCreateTable(table.rows, table.columns);
}
```
So that I can do
```zig
zgui.createTable(.{.columns = 5});
```

**Comment by Bergasms** [comment]
Yep, can do

**Pull request merged**
